workflows:
  expo-android-apk:
    name: Expo Android APK

    environment:
      node: 20

    scripts:
      - npm ci
      - npx expo --version
      - npx expo prebuild
      - cd android
      - chmod +x gradlew
      - ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk