workflows:
  expo-android-apk:
    name: Expo Android APK

    max_build_duration: 60

    environment:
      node: 20
      npm: 10

    scripts:
      - rm -rf node_modules
      - rm -f package-lock.json
      - npm cache clean --force
      - npm install --legacy-peer-deps
      - npx expo prebuild --platform android
      - cd android
      - chmod +x gradlew
      - ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk