workflows:
  expo-android-apk:
    name: Expo Android APK

    max_build_duration: 60

    environment:
      node: 20

    cache:
      cache_paths:
        - ~/.npm

    scripts:
      - npm install
      - npx expo install
      - npx expo prebuild --platform android
      - cd android
      - chmod +x gradlew
      - ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk